# Generated by Django 5.0.3 on 2024-04-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memorial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("num_obtuario", models.CharField(max_length=100)),
                ("falecido", models.CharField(max_length=100)),
                ("data_falecimento", models.CharField(max_length=100)),
                ("sexo", models.CharField(max_length=100)),
                ("cor", models.CharField(max_length=100)),
                ("data_nascimento", models.CharField(max_length=100)),
                ("detalhes", models.CharField(max_length=100)),
                ("idade", models.CharField(max_length=100))
            ],
            options={
                "verbose_name": "Memorial",
                "verbose_name_plural": "Memorial",
            },
        ),
    ]
